/*  stdfunc7.inc

    March 16, 2005

    SCIPS.com, Inc.

    Standard Functions items for SCIPS Version 7
*/
Add						Tagged Add_fn;
Change					Tagged Change_fn;
Delete					Tagged Delete_fn;
Search					Tagged Search_fn;
Find						Tagged Find_fn;
Next						Tagged Next_fn;
Previous  				Tagged Previous_fn;
Page/noreturn				Tagged Page_fn;
"BACK"	Sequence "EXIT" 	Tagged Back_fn;
"EXIT"	return			Tagged Exit_fn;
Return					Tagged Return_fn;
Print					Tagged Print_fn;
