/*  styles.inc 

    March 15, 2005

    SCIPS.com, Inc.

    styles include file to be used with ALL SCIPS Version 7
    screens
*/

Style {
	 ForeGroundColor = "#00000f"
	 CursorShape     = HAND
	 }  tagged Hyperlink_S

Style {
      FontName        = "Verdana"
	 FontStyle       = "Italic"
	 FontSize        = 12
	 }  tagged Big_Font_Italic 

Style {
      FontName        = "Verdana"
	 FontSize        = 12
	 }  tagged Big_Font

Style {
      FontName        = "Verdana"
	 FontSize        = 10
	 }  tagged Normal_Font

Style {
      FontName        = "Verdana"
	 FontStyle       = "Italic"
	 FontSize        = 10
	 }  tagged Normal_Font_Italic 

Style {
	 ForeGroundColor = Java "new color.red"
	 BackGroundColor = Java "new color.white"
	 Cursor          = Java "Cursor.getPredefinedCursor(Cursor.Hand_Cursor)"
	 Font            = Java 'new font("sansserif", font.bold, 10)'
	 }  tagged Java_Hyperlink_red

Style {
	 ForeGroundColor = Java "new color.blue"
	 BackGroundColor = Java "new color.white"
	 Cursor          = Java "Cursor.getPredefinedCursor(Cursor.Hand_Cursor)"
	 Font            = Java 'new font("sansserif", font.bold, 10)'
	 }  tagged Java_Hyperlink_blue

Style {
	 ForeGroundColor = Java "new color.green"
	 BackGroundColor = Java "new color.white"
	 Cursor          = Java "Cursor.getPredefinedCursor(Cursor.Hand_Cursor)"
	 Font            = Java 'new font("sansserif", font.bold, 10)'
	 }  tagged Java_Hyperlink_green

Style {
	 ForeGroundColor = Java "new color.orange"
	 BackGroundColor = Java "new color.white"
	 Cursor          = Java "Cursor.getPredefinedCursor(Cursor.Hand_Cursor)"
	 Font            = Java 'new font("sansserif", font.bold, 10)'
	 }  tagged Java_Hyperlink_orange

Style {
	 ForeGroundColor = Java "new color.yellow"
	 BackGroundColor = Java "new color.white"
	 Cursor          = Java "Cursor.getPredefinedCursor(Cursor.Hand_Cursor)"
	 Font            = Java 'new font("sansserif", font.bold, 10)'
	 }  tagged Java_Hyperlink_yellow

Style {
      FontName        = "SansSerif"
	 FontSize        = 8
	 }  tagged Normal_Font_small

